#!/bin/sh 
modulo=$1 
#count page numbers
p=$(pdfinfo $2 | grep Pages | sed 's/[^0-9]*//') 
# prepare for removal of backcover
endpage=$(($p - 4))  #remove ad
effectivepages=$(($p - 4)) 
blankpagenumber=$(($p - 3))  
# compute how many blank pages to add
n=$(($modulo -  $effectivepages % modulo)) 
# start with no blank pages
b=''
#accumulate Bs until we reach a multiple
while [ $n -ne 0 ]; do
  b=$b\ A$blankpagenumber
  n=$(($n - 1))
  done
echo $b 
# strip front and back cover and add blank pages to meet multiple of modulo
pdftk A=$2 cat A$blankpagenumber A2-$endpage $b output $3

